#!/usr/bin/env perl
use Mojolicious::Lite;
use lib 'lib';
use DB;

helper db => sub {
  return DB->new();
};

# e.g.
get '/' => sub {
  my $c = shift;
  app->log->info( 'user_id : '.$c->param('user_id') );
  $c->render( json => $c->db->export_user( user_id => $c->param('user_id') ) );
};


app->start;
__DATA__

@@ index.html.ep
% layout 'default';
% title 'Welcome';
<h1>Welcome to the Mojolicious real-time web framework!</h1>
To learn more, you can browse through the documentation
<%= link_to 'here' => '/perldoc' %>.

@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
  <head><title><%= title %></title></head>
  <body><%= content %></body>
</html>
